"""Stable shared interfaces for task configuration, training, and evaluation."""

from .base_config import (
    BaseConfig,
    TaskConfig,
    load_config,
    save_config,
    set_config_default_if_not_explicit,
    task_config_from_dict,
)
from .checkpoint import (
    CheckpointManager,
    load_checkpoint,
    resolve_checkpoint_file,
    unwrap_model,
)
from .data import (
    make_file_split_dataloaders,
    make_dataloader_kwargs,
    make_worker_init_fn,
    split_items,
    resolve_data_path,
)
from .distributed import (
    DistributedSamplerAdapter,
    DistributedState,
    barrier,
    cleanup_distributed,
    distributed_enabled,
    init_distributed,
    make_default_eval_sampler,
    make_default_train_sampler,
    reduce_dict,
    shard_sampler_for_distributed,
    wrap_model_for_distributed,
)
from .metrics import MetricAverager, MetricStat
from .utils import (
    JsonlLogger,
    format_seconds,
    import_from_path,
    resolve_device,
    resolve_optimizer,
    set_seed,
    to_jsonable,
)
from .base_runner import (
    BaseRunner,
    RunnerOutput,
    build_runner,
    build_runner_from_checkpoint,
    move_to_device,
    resolve_runner_class,
)

__all__ = [
    "BaseConfig",
    "TaskConfig",
    "task_config_from_dict",
    "load_config",
    "save_config",
    "set_config_default_if_not_explicit",
    "CheckpointManager",
    "load_checkpoint",
    "resolve_checkpoint_file",
    "unwrap_model",
    "make_file_split_dataloaders",
    "make_dataloader_kwargs",
    "make_worker_init_fn",
    "split_items",
    "resolve_data_path",
    "DistributedSamplerAdapter",
    "DistributedState",
    "barrier",
    "cleanup_distributed",
    "distributed_enabled",
    "init_distributed",
    "make_default_eval_sampler",
    "make_default_train_sampler",
    "reduce_dict",
    "shard_sampler_for_distributed",
    "wrap_model_for_distributed",
    "JsonlLogger",
    "MetricAverager",
    "MetricStat",
    "format_seconds",
    "import_from_path",
    "resolve_device",
    "resolve_optimizer",
    "set_seed",
    "to_jsonable",
    "BaseRunner",
    "RunnerOutput",
    "build_runner",
    "build_runner_from_checkpoint",
    "move_to_device",
    "resolve_runner_class",
]
